# Generated by Django 5.2.3 on 2025-06-16 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المدينة')),
                ('region', models.CharField(choices=[('riyadh', 'الرياض'), ('makkah', 'مكة المكرمة'), ('madinah', 'المدينة المنورة'), ('eastern', 'المنطقة الشرقية'), ('asir', 'عسير'), ('tabuk', 'تبوك'), ('hail', 'حائل'), ('northern_border', 'الحدود الشمالية'), ('jazan', 'جازان'), ('najran', 'نجران'), ('bahah', 'الباحة'), ('jawf', 'الجوف'), ('qassim', 'القصيم')], max_length=20, verbose_name='المنطقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مدينة',
                'verbose_name_plural': 'المدن',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BloodBankProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodbank_name', models.CharField(max_length=150, verbose_name='اسم بنك الدم')),
                ('hospital_name', models.CharField(max_length=150, verbose_name='اسم المستشفى التابع له')),
                ('region', models.CharField(choices=[('riyadh', 'الرياض'), ('makkah', 'مكة المكرمة'), ('madinah', 'المدينة المنورة'), ('eastern', 'المنطقة الشرقية'), ('asir', 'عسير'), ('tabuk', 'تبوك'), ('hail', 'حائل'), ('northern_border', 'الحدود الشمالية'), ('jazan', 'جازان'), ('najran', 'نجران'), ('bahah', 'الباحة'), ('jawf', 'الجوف'), ('qassim', 'القصيم')], max_length=20, verbose_name='المنطقة')),
                ('contact_number', models.CharField(max_length=20, verbose_name='رقم التواصل')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('map_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='إحداثيات الموقع')),
                ('working_hours', models.CharField(max_length=100, verbose_name='أوقات العمل (الأيام - الساعات)')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='تعليمات خاصة')),
                ('manager_name', models.CharField(max_length=100, verbose_name='اسم المسؤول')),
                ('manager_phone', models.CharField(max_length=20, verbose_name='رقم هاتف المسؤول')),
                ('manager_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني للمسؤول')),
                ('manager_position', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تم اعتماد العضوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.city', verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'بيانات بنك الدم',
                'verbose_name_plural': 'بيانات بنوك الدم',
            },
        ),
    ]
