# Generated by Django 5.2.3 on 2025-06-16 05:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='اسم المريض')),
                ('medical_file_number', models.CharField(max_length=50, verbose_name='رقم الملف الطبي')),
                ('hospital_name', models.CharField(max_length=200, verbose_name='اسم المستشفى')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='فصيلة الدم المطلوبة')),
                ('blood_component', models.CharField(choices=[('whole', 'دم كامل'), ('plasma', 'بلازما'), ('platelets', 'صفائح دموية'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الدم المطلوب')),
                ('patient_age', models.PositiveIntegerField(verbose_name='عمر المريض')),
                ('patient_gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='جنس المريض')),
                ('units_needed', models.PositiveIntegerField(verbose_name='عدد الوحدات المطلوبة')),
                ('is_critical', models.BooleanField(default=False, verbose_name='حالة حرجة')),
                ('contact_number', models.CharField(max_length=20, verbose_name='رقم للتواصل')),
                ('additional_info', models.TextField(verbose_name='وصف إضافي للحالة')),
                ('medical_report', models.FileField(upload_to='medical_reports/', verbose_name='التقرير الطبي')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'قيد التحقق'), ('approved', 'تم التحقق'), ('rejected', 'مرفوض'), ('completed', 'منتهي'), ('upcoming', 'قادم')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الطلب')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.city', verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'طلب تبرع بالدم',
                'verbose_name_plural': 'طلبات التبرع بالدم',
                'ordering': ['-created_at'],
            },
        ),
    ]
