# Generated by Django 5.2.3 on 2025-06-16 05:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان الرئيسي')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='العنوان الفرعي')),
                ('summary', models.TextField(max_length=240, verbose_name='ملخص الخبر')),
                ('content', models.TextField(verbose_name='نص الخبر')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='news/articles/', verbose_name='الصورة الرئيسية')),
                ('status', models.CharField(choices=[('published', 'منشور'), ('cancelled', 'ملغي'), ('pending', 'قيد التحقق'), ('scheduled', 'بانتظار النشر'), ('deleted', 'محذوف')], default='pending', max_length=20, verbose_name='حالة النشر')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'الأخبار',
                'ordering': ['-publish_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/attachments/', verbose_name='صورة مرفقة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='news.newsarticle', verbose_name='الخبر')),
            ],
            options={
                'verbose_name': 'صورة مرفقة للخبر',
                'verbose_name_plural': 'الصور المرفقة للأخبار',
            },
        ),
        migrations.CreateModel(
            name='NewsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='وصف مختصر')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='news/sections/', verbose_name='صورة رمزية')),
                ('status', models.CharField(choices=[('active', 'مفعل'), ('inactive', 'موقوف مؤقتًا'), ('deleted', 'محذوف')], default='active', max_length=20, verbose_name='الحالة')),
                ('target_audience', models.CharField(blank=True, max_length=100, verbose_name='الفئة المستهدفة')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='أولوية الظهور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign', verbose_name='حملة مرتبطة')),
            ],
            options={
                'verbose_name': 'قسم أخبار',
                'verbose_name_plural': 'أقسام الأخبار',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.newssection', verbose_name='القسم الفرعي'),
        ),
    ]
