# Generated by Django 5.2.3 on 2025-06-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_color', models.CharField(default='#b30000', help_text='اللون الرئيسي للموقع (الأزرار، العناوين)', max_length=7)),
                ('secondary_color', models.CharField(default='#fff', help_text='اللون الثانوي (خلفية البطاقات)', max_length=7)),
                ('background_color', models.CharField(default='#f7f8fa', help_text='لون خلفية الموقع', max_length=7)),
                ('navbar_color', models.CharField(default='#b30000', help_text='لون شريط التنقل العلوي', max_length=7)),
                ('navbar_text_color', models.CharField(default='#fff', help_text='لون نص شريط التنقل', max_length=7)),
                ('footer_color', models.CharField(default='#1a2940', help_text='لون خلفية الفوتر', max_length=7)),
                ('footer_text_color', models.CharField(default='#fff', help_text='لون نص الفوتر', max_length=7)),
                ('card_radius', models.CharField(default='18px', help_text='درجة انحناء زوايا البطاقات', max_length=5)),
                ('card_shadow', models.CharField(default='0 2px 16px #e6e6e6', help_text='تأثير ظل البطاقات', max_length=100)),
                ('button_radius', models.CharField(default='18px', help_text='درجة انحناء زوايا الأزرار', max_length=5)),
                ('button_shadow', models.CharField(default='none', help_text='تأثير ظل الأزرار', max_length=100)),
                ('button_hover_color', models.CharField(default='#8c0000', help_text='لون الزر عند التحويم', max_length=7)),
                ('text_color', models.CharField(default='#222', help_text='لون النص الأساسي', max_length=7)),
                ('muted_text_color', models.CharField(default='#888', help_text='لون النص الثانوي/المساعد', max_length=7)),
                ('heading_font', models.CharField(default="'Cairo', sans-serif", help_text='خط العناوين', max_length=100)),
                ('body_font', models.CharField(default="'Cairo', sans-serif", help_text='خط النصوص', max_length=100)),
                ('border_color', models.CharField(default='#e6e6e6', help_text='لون حدود البطاقات والعناصر', max_length=7)),
                ('link_color', models.CharField(default='#b30000', help_text='لون الروابط', max_length=7)),
                ('link_hover_color', models.CharField(default='#8c0000', help_text='لون الروابط عند التحويم', max_length=7)),
                ('success_color', models.CharField(default='#28a745', help_text='لون النجاح/التنبيهات الإيجابية', max_length=7)),
                ('warning_color', models.CharField(default='#ffc107', help_text='لون التحذير', max_length=7)),
                ('danger_color', models.CharField(default='#dc3545', help_text='لون الخطر/الأخطاء', max_length=7)),
                ('info_color', models.CharField(default='#17a2b8', help_text='لون المعلومات', max_length=7)),
                ('border_radius_global', models.CharField(default='18px', help_text='درجة انحناء الزوايا العامة', max_length=5)),
            ],
            options={
                'verbose_name': 'إعدادات التصميم',
                'verbose_name_plural': 'إعدادات التصميم',
            },
        ),
    ]
