# Generated by Django 5.2.3 on 2025-06-17 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='العنوان الرئيسي')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='العنوان الفرعي')),
                ('icons', models.JSONField(blank=True, help_text="مثال: [{icon: 'fa-bullhorn', url: 'https://...'}]", null=True, verbose_name='الأيقونات والروابط')),
                ('background_type', models.CharField(choices=[('color', 'لون ثابت'), ('gradient', 'تدرج لوني'), ('image', 'صورة')], default='color', max_length=20, verbose_name='نوع الخلفية')),
                ('background_color', models.CharField(blank=True, max_length=32, verbose_name='لون الخلفية')),
                ('background_gradient', models.CharField(blank=True, max_length=128, verbose_name='تدرج الخلفية (CSS)')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='صورة الخلفية')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت بداية النشر')),
                ('duration_seconds', models.PositiveIntegerField(default=10, verbose_name='مدة العرض بالثواني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('ended', 'منتهي'), ('scheduled', 'قيد الانتظار')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('places', models.JSONField(default=list, verbose_name='أماكن الظهور')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب البنر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بنر إعلاني',
                'verbose_name_plural': 'بنرات إعلانية',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
