# Generated by Django 5.2.3 on 2025-06-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bannerbutton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='icons',
        ),
    ]
