# Generated by Django 5.2.3 on 2025-06-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_banner_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='content_alignment',
            field=models.CharField(choices=[('center', 'وسط'), ('start', 'يسار'), ('end', 'يمين')], default='center', max_length=10, verbose_name='محاذاة المحتوى'),
        ),
    ]
