# Generated by Django 5.2.3 on 2025-06-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_banner_content_alignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerbutton',
            name='banner',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='BannerButton',
        ),
    ]
