# Generated by Django 5.2.3 on 2025-06-16 05:11

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المدينة')),
                ('region', models.CharField(choices=[('riyadh', 'الرياض'), ('makkah', 'مكة المكرمة'), ('madinah', 'المدينة المنورة'), ('eastern', 'المنطقة الشرقية'), ('asir', 'عسير'), ('tabuk', 'تبوك'), ('hail', 'حائل'), ('northern_border', 'الحدود الشمالية'), ('jazan', 'جازان'), ('najran', 'نجران'), ('bahah', 'الباحة'), ('jawf', 'الجوف'), ('qassim', 'القصيم')], max_length=20, verbose_name='المنطقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مدينة',
                'verbose_name_plural': 'المدن',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_required', models.BooleanField(default=True, verbose_name='تفعيل التحقق')),
                ('verify_email', models.BooleanField(default=True, verbose_name='تفعيل التحقق بالبريد الإلكتروني')),
                ('verify_phone', models.BooleanField(default=True, verbose_name='تفعيل التحقق بالجوال')),
                ('require_full_name', models.BooleanField(default=True, verbose_name='الاسم الثلاثي')),
                ('require_age', models.BooleanField(default=True, verbose_name='العمر')),
                ('require_nationality', models.BooleanField(default=True, verbose_name='الجنسية')),
                ('require_city', models.BooleanField(default=True, verbose_name='المدينة')),
                ('require_blood_type', models.BooleanField(default=True, verbose_name='فصيلة الدم')),
                ('require_previous_donation', models.BooleanField(default=True, verbose_name='التبرع السابق')),
                ('require_chronic_diseases', models.BooleanField(default=True, verbose_name='الأمراض المزمنة')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=30, verbose_name='الاسم الأول')),
                ('middle_name', models.CharField(max_length=30, verbose_name='اسم الأب')),
                ('last_name', models.CharField(max_length=30, verbose_name='اسم العائلة')),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'رقم الجوال يجب أن يكون 10 أرقام')], verbose_name='رقم الجوال')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('username', models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$', 'اسم المستخدم يجب أن يكون أحرف وأرقام إنجليزية فقط')], verbose_name='اسم المستخدم')),
                ('avatar', models.ImageField(blank=True, default='images/default-avatar.png', null=True, upload_to='avatars/', verbose_name='الصورة الرمزية')),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, null=True, verbose_name='الجنس')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='العمر')),
                ('region', models.CharField(choices=[('riyadh', 'الرياض'), ('makkah', 'مكة المكرمة'), ('madinah', 'المدينة المنورة'), ('eastern', 'المنطقة الشرقية'), ('asir', 'عسير'), ('tabuk', 'تبوك'), ('hail', 'حائل'), ('northern_border', 'الحدود الشمالية'), ('jazan', 'جازان'), ('najran', 'نجران'), ('bahah', 'الباحة'), ('jawf', 'الجوف'), ('qassim', 'القصيم')], max_length=20, verbose_name='المنطقة')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي')),
                ('social_accounts', models.JSONField(blank=True, default=dict, null=True, verbose_name='حسابات التواصل الاجتماعي')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=3, verbose_name='فصيلة الدم')),
                ('has_donated', models.BooleanField(default=False, verbose_name='هل سبق لك التبرع بالدم؟')),
                ('previous_blood_bank', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم بنك الدم الذي تبرعت فيه مؤخرًا')),
                ('has_chronic_disease', models.BooleanField(default=False, verbose_name='هل لديك أمراض مزمنة؟')),
                ('chronic_disease_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المرض المزمن')),
                ('privacy', models.CharField(choices=[('public', 'عام'), ('members', 'للأعضاء فقط'), ('private', 'خاص')], default='members', max_length=20, verbose_name='خصوصية الملف')),
                ('donation_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات التبرع')),
                ('badges', models.JSONField(blank=True, default=dict, null=True, verbose_name='الشارات/الأوسمة')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='رمز التحقق')),
                ('verification_code_created_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إنشاء رمز التحقق')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='رمز التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('is_used', models.BooleanField(default=False, verbose_name='تم الاستخدام')),
                ('verification_method', models.CharField(choices=[('email', 'البريد الإلكتروني'), ('phone', 'الجوال')], max_length=10, verbose_name='طريقة التحقق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز تحقق',
                'verbose_name_plural': 'رموز التحقق',
            },
        ),
    ]
