# Generated by Django 5.2.3 on 2025-06-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBankUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='اسم المستخدم')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('bloodbank_name', models.CharField(max_length=150, verbose_name='اسم بنك الدم')),
                ('hospital_name', models.CharField(max_length=150, verbose_name='اسم المستشفى التابع له')),
                ('region', models.CharField(max_length=20, verbose_name='المنطقة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('contact_number', models.CharField(max_length=20, verbose_name='رقم التواصل')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('map_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='إحداثيات الموقع')),
                ('working_hours', models.CharField(max_length=100, verbose_name='أوقات العمل (الأيام - الساعات)')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='تعليمات خاصة')),
                ('manager_name', models.CharField(max_length=100, verbose_name='اسم المسؤول')),
                ('manager_phone', models.CharField(max_length=20, verbose_name='رقم هاتف المسؤول')),
                ('manager_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني للمسؤول')),
                ('manager_position', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False, verbose_name='تم اعتماد العضوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='bloodbankuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='bloodbankuser_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'عضوية بنك دم',
                'verbose_name_plural': 'عضويات بنوك الدم',
            },
        ),
    ]
