# Generated by Django 5.2.3 on 2025-06-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الحالة')),
                ('blood_component', models.CharField(choices=[('whole', 'دم كامل'), ('plasma', 'بلازما'), ('platelets', 'صفائح دموية')], max_length=20, verbose_name='نوع الدم المطلوب')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='فصيلة الدم المطلوبة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('hospital_name', models.CharField(max_length=255, verbose_name='اسم المستشفى')),
                ('location_url', models.URLField(blank=True, null=True, verbose_name='رابط الموقع الجغرافي')),
                ('units_needed', models.PositiveIntegerField(verbose_name='عدد الوحدات المطلوبة')),
                ('is_critical', models.BooleanField(default=False, verbose_name='هل الحالة حرجة؟')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('age', models.PositiveIntegerField(verbose_name='العمر')),
                ('contact_number', models.CharField(max_length=20, verbose_name='رقم التواصل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف إضافي')),
                ('medical_report', models.FileField(blank=True, null=True, upload_to='medical_reports/', verbose_name='تقرير طبي')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('review', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المشرف')),
            ],
        ),
    ]
