# Generated by Django 5.2.3 on 2025-06-16 05:11

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الحملة')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='campaigns/covers/', verbose_name='الصورة الرمزية')),
                ('description', tinymce.models.HTMLField(verbose_name='وصف الحملة')),
                ('location_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الموقع/المقر')),
                ('google_maps_url', models.URLField(blank=True, null=True, verbose_name='رابط Google Maps')),
                ('region', models.CharField(blank=True, choices=[('riyadh', 'الرياض'), ('makkah', 'مكة المكرمة'), ('madinah', 'المدينة المنورة'), ('eastern', 'المنطقة الشرقية'), ('asir', 'عسير'), ('tabuk', 'تبوك'), ('hail', 'حائل'), ('northern_border', 'الحدود الشمالية'), ('jazan', 'جازان'), ('najran', 'نجران'), ('bahah', 'الباحة'), ('jawf', 'الجوف'), ('qassim', 'القصيم')], max_length=20, null=True, verbose_name='المنطقة')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي')),
                ('organizer_bank', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم بنك الدم المنظم')),
                ('partners', models.CharField(blank=True, max_length=255, null=True, verbose_name='الشركاء (اختياري)')),
                ('supervisor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المشرف/المنسق')),
                ('supervisor_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم التواصل للمشرف')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('upcoming', 'قادمة'), ('active', 'جارية'), ('ended', 'منتهية'), ('draft', 'مسودة'), ('cancelled', 'ملغاة')], default='upcoming', max_length=20, verbose_name='حالة الحملة')),
                ('manual_status', models.BooleanField(default=False, verbose_name='تفعيل التحكم اليدوي بالحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaigns/gallery/', verbose_name='صورة إضافية')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف للصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='campaigns.campaign', verbose_name='الحملة')),
            ],
        ),
    ]
