# Generated by Django 5.2.3 on 2025-06-16 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(verbose_name='محتوى الإشعار')),
                ('notification_type', models.CharField(choices=[('blood_request', 'طلب تبرع بالدم'), ('campaign', 'حملة تبرع'), ('system', 'إشعار نظام'), ('alert', 'تنبيه عاجل')], max_length=20, verbose_name='نوع الإشعار')),
                ('recipient', models.CharField(max_length=255, verbose_name='المستلم')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('sent', 'تم الإرسال'), ('failed', 'فشل الإرسال')], default='pending', max_length=20, verbose_name='حالة الإشعار')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
